-- ============================================================================
-- migration: 20251121125841_cron_notifications.sql
-- description: create notifications table and pg_cron job for session reminders
-- purpose: enable session follow-up notifications (user story 4)
-- affected tables: notifications
-- special considerations:
--   - pg_cron runs daily at 6am utc to generate session reminders
--   - notifications include previous session summary and follow-up items
--   - deduplication prevents multiple notifications for same client/date
--   - rls ensures practitioners only see their own notifications
-- ============================================================================

-- ============================================================================
-- table: notifications
-- description: session reminders and system notifications
-- generated by: pg_cron job (session reminders) or application (system notifications)
-- ============================================================================

create table notifications (
  id uuid primary key default gen_random_uuid(),
  practitioner_id uuid not null references profiles(id) on delete cascade,
  client_id uuid references clients(id) on delete cascade,
  note_id uuid references notes(id) on delete set null, -- related note for context

  type text not null check (type in ('session_reminder', 'system', 'info')),
  title text not null,
  content jsonb not null, -- notification payload with session details

  viewed boolean default false,
  viewed_at timestamptz,

  created_at timestamptz default now()
);

-- indexes for efficient querying
create index idx_notifications_practitioner_id on notifications(practitioner_id);
create index idx_notifications_client_id on notifications(client_id);
create index idx_notifications_viewed on notifications(viewed) where viewed = false; -- partial index for unread
create index idx_notifications_created_at on notifications(created_at desc);

-- enable rls
alter table notifications enable row level security;

-- ============================================================================
-- rls policies: notifications
-- rationale: practitioners should only see their own notifications
-- ============================================================================

create policy "authenticated practitioners can view own notifications"
  on notifications for select
  to authenticated
  using (auth.uid() = practitioner_id);

create policy "authenticated practitioners can update own notifications"
  on notifications for update
  to authenticated
  using (auth.uid() = practitioner_id);

-- ============================================================================
-- enable pg_cron extension
-- description: allows scheduling of recurring jobs within postgres
-- ============================================================================

create extension if not exists pg_cron;

-- ============================================================================
-- cron job: generate session notifications
-- schedule: runs daily at 6:00 am utc
-- description: generates notifications for practitioners with scheduled sessions today
-- logic:
--   1. finds notes with next_session_date = current_date
--   2. includes notes with follow_up_items (commitments from previous session)
--   3. only approved notes (not drafts)
--   4. deduplicates to prevent multiple notifications for same client/date
--   5. includes previous session summary and follow-up items in payload
-- ============================================================================

select cron.schedule(
  'generate-session-notifications',
  '0 6 * * *', -- cron expression: 6 am daily
  $$
  insert into notifications (practitioner_id, client_id, note_id, type, title, content)
  select
    n.practitioner_id,
    n.client_id,
    n.id as note_id,
    'session_reminder' as type,
    'upcoming session: ' || c.full_name as title,
    json_build_object(
      'scheduled_date', n.next_session_date,
      'previous_session_summary', left(n.markdown_content, 200), -- first 200 chars as summary
      'follow_ups', n.follow_up_items,
      'session_count', (
        select count(*) from notes
        where client_id = n.client_id and status = 'approved'
      )
    ) as content
  from notes n
  join clients c on c.id = n.client_id
  where n.next_session_date = current_date
    and n.follow_up_items is not null
    and array_length(n.follow_up_items, 1) > 0 -- ensure follow_up_items is not empty
    and n.status = 'approved'
    and not exists (
      select 1 from notifications notif
      where notif.client_id = n.client_id
        and notif.type = 'session_reminder'
        and notif.created_at::date = current_date
    );
  $$
);

-- ============================================================================
-- optional: view cron job status
-- description: query to check if cron job is scheduled correctly
-- usage: select * from cron.job;
-- ============================================================================

-- uncomment to verify cron job creation:
-- select jobid, schedule, command, nodename, nodeport, database, username, active
-- from cron.job
-- where jobname = 'generate-session-notifications';
